# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AssignmentChalkboard' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwiftyJSONDecoder'

  pod 'JGProgressHUD'

  target 'AssignmentChalkboardTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AssignmentChalkboardUITests' do
    # Pods for testing
  end

end
